"""Initial migration

Revision ID: 9f02e33dd29d
Revises: 
Create Date: 2026-05-25 16:17:07.999497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f02e33dd29d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hallucination_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('registry', sa.Enum('PYPI', 'NPM', 'CRATES', 'GO', name='registryenum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('suggestion_count', sa.Integer(), nullable=True),
    sa.Column('is_verified_hallucination', sa.Boolean(), nullable=True),
    sa.Column('registered_malicious', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hallucination_candidates_package_name'), 'hallucination_candidates', ['package_name'], unique=False)
    op.create_table('maintainers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registry', sa.Enum('PYPI', 'NPM', 'CRATES', 'GO', name='registryenum'), nullable=False),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('github_verified', sa.Boolean(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registry', sa.Enum('PYPI', 'NPM', 'CRATES', 'GO', name='registryenum'), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('merkle_proof', sa.String(), nullable=True),
    sa.Column('sigstore_bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_name'), 'packages', ['name'], unique=False)
    op.create_table('trust_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_snapshots_snapshot_version'), 'trust_snapshots', ['snapshot_version'], unique=False)
    op.create_table('package_maintainers',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('maintainer_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maintainer_id'], ['maintainers.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('package_id', 'maintainer_id')
    )
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('download_count', sa.BigInteger(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('malware_score', sa.Float(), nullable=True),
    sa.Column('cve_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_table('versions')
    op.drop_table('package_maintainers')
    op.drop_index(op.f('ix_trust_snapshots_snapshot_version'), table_name='trust_snapshots')
    op.drop_table('trust_snapshots')
    op.drop_index(op.f('ix_packages_name'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('maintainers')
    op.drop_index(op.f('ix_hallucination_candidates_package_name'), table_name='hallucination_candidates')
    op.drop_table('hallucination_candidates')
    # ### end Alembic commands ###
